name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: actions/setup-python@v3

      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Push Docker image to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        run: docker tag my-docker-image docker.pkg.github.com/${{ github.repository }}/my-docker-image:latest
        run: docker push docker.pkg.github.com/${{ github.repository }}/my-docker-image:latest

      - name: Deploy to GitHub Pages
        run: |
          docker compose stop && docker compose up --build